bonsai/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from core import views
from core import project_views
from core import subject_views
from core import sample_views
from analysis import views as analysis_views
import settings
from django.views.generic.simple import direct_to_template
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
	# LOGIN/LOGOUT
    (r'^$', views.index),
    (r'^about/$', direct_to_template, {'template': 'about.html'}),
    (r'^help/$', direct_to_template, {'template': 'help.html'}),
    (r'^user/logout/$', views.logout_user),
    (r'^user/settings/$', views.set_user_profile),
    (r'^user/subscribe/(?P<project_id>\d+)$', project_views.subscribe_user),
    (r'^user/unsubscribe/(?P<project_id>\d+)$', project_views.unsubscribe_user),
    (r'^user/subscription/notify/(?P<subscription_id>\d+)$', project_views.notify_user),
    (r'^user/subscription/denotify/(?P<subscription_id>\d+)$', project_views.denotify_user),
    (r'^subjects/list/(?P<project_id>\d+)/(?P<page_num>\d+)$', subject_views.show_by_project),
    (r'^subjects/list/byuser/(?P<page_num>\d+)$', subject_views.show_by_user),
    (r'^samples/list/byproject/(?P<project_id>\d+)/(?P<page_num>\d+)$', sample_views.show_by_project),
    (r'^samples/list/bysubject/(?P<subject_id>\d+)/(?P<page_num>\d+)$', sample_views.show_by_subject),
    (r'^samples/list/byuser/(?P<page_num>\d+)$', sample_views.show_by_user),
    #Bookmarks
    (r'^bookmark/subject/show/(?P<page_num>\d+)$', subject_views.show_bookmarks),
    (r'^bookmark/subject/add/(?P<subject_id>\d+)$', subject_views.add_bookmark),
    (r'^bookmark/subject/remove/(?P<subject_id>\d+)$', subject_views.remove_bookmark),
    (r'^bookmark/sample/show/(?P<page_num>\d+)$', sample_views.show_bookmarks),
    (r'^bookmark/sample/add/(?P<sample_id>\d+)$', sample_views.add_bookmark),
    (r'^bookmark/sample/remove/(?P<sample_id>\d+)$', sample_views.remove_bookmark),

    # CRUD
    (r'^project/list/(?P<page_num>\d+)$', project_views.list),
    (r'^project/list/subscribed$', project_views.list_subscribed),
    (r'^project/add/$', project_views.add),
    (r'^project/show/(\d+)$', project_views.show),
    (r'^project/edit/(\d+)$', project_views.edit),
    (r'^project/delete/(\d+)$', project_views.delete),
    (r'^project/show/samples/(?P<project_id>\d+)/(?P<page_length>\d+)/(?P<goto_page>\d+)', project_views.samples),
    (r'^subject/add/$', subject_views.add),
    (r'^subject/show/(\d+)$', subject_views.show),
    (r'^subject/edit/(\d+)$', subject_views.edit),
    (r'^subject/delete/(\d+)$', subject_views.delete),
    (r'^sample/add$', sample_views.add),
    (r'^sample/show/(\d+)$', sample_views.show),
    (r'^sample/edit/(\d+)$', sample_views.edit),
    (r'^sample/delete/(\d+)$', sample_views.delete),
    (r'^sample/search$', sample_views.search),
    (r'^sample/aliquot/new/(?P<sample_id>\d+)$', sample_views.add_aliquot),
    # JSON API
    (r'^json/project/get/(\d+)$', project_views.json_samples_by_project),
    (r'^json/projects/all/', project_views.json_all_projects),
    # ANALYSIS
    (r'^analysis/attr/add$', analysis_views.add),
    (r'^analysis/main/add/analysis/(?P<sample_id>\d+)', analysis_views.add_analysis),
    (r'^analysis/main/add/analysis_type$', analysis_views.add_analysis_type),
	(r'^analysis/main/manage/(?P<sample_id>\d+)', analysis_views.main_manage),
    (r'^analysis/bysample/(?P<sample_id>\d+)$', analysis_views.add ),
    (r'^analysis/main/(?P<sample_id>\d+)$', analysis_views.main_view ),
    (r'^analysis/show/bysample/(?P<sample_id>\d+)/(?P<page_num>\d+)$', analysis_views.show_by_sample ),
    (r'^analysis/attributes/bysample/(?P<sample_id>\d+)$', analysis_views.get_sample_attributes),
    (r'^analysis/attributes/byanalysis_type/(?P<analysis_type_id>\d+)$', analysis_views.get_attributes_by_analysis_type),
    (r'^analysis/edit/(?P<analysis_id>\d+)$', analysis_views.edit ),
    (r'^analysis/delete/(?P<analysis_id>\d+)$', analysis_views.delete ),
    # ADMIN
    url(r'^admin/', include(admin.site.urls)),
    (r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
)
urlpatterns += staticfiles_urlpatterns()

bonsai/analysis/models.py
from django.db import models
from core import models as core_models

from django.contrib.auth.models import User

# Create your models here.
class AnalysisType(models.Model):
	name = models.CharField(max_length=30,verbose_name="* Name")
	description = models.CharField(max_length=30, null=True, blank=True)
	protocol_url = models.URLField(null=True, blank=True)
	date_time_last_updated = models.DateTimeField()
	last_updated_by = models.ForeignKey(User)

	def __unicode__(self):
		return self.name

class AnalysisAttribute(models.Model):
	analysis_type = models.ForeignKey(AnalysisType, verbose_name="* Analysis type")
	sample = models.ForeignKey(core_models.Sample, related_name="analysis_attributes", verbose_name="* Sample")
	name = models.CharField(max_length=30, verbose_name="* Name")
	value = models.CharField(max_length=50, null=True, blank=True)
	aliquot_id = models.CharField(max_length=50, verbose_name="* Aliquot id")
	last_updated_by = models.ForeignKey(User)
	date_time_last_updated = models.DateTimeField()
	def  __unicode__(self):
		return self.name

bonsai/analysis/forms.py
from django import forms
from models import AnalysisType
from django.shortcuts import render_to_response
from core.models import Sample
from models import AnalysisType, AnalysisAttribute

class AddAnalysisForm(forms.ModelForm):
	class Meta:
		model = AnalysisAttribute
		fields = ['name', 'value', 'analysis_type', 'sample', 'aliquot_id',]

class AddAnalysisTypeForm(forms.ModelForm):
	class Meta:
		model = AnalysisType
		fields = ['name', 'protocol_url', 'description']

bonsai/analysis/views.py
	# Create your views here.
from django.shortcuts import render_to_response
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from core.models import Sample, Subject, Project
import forms
import datetime
import models
from django.utils import simplejson
from django.forms.models import modelformset_factory
from django.core.paginator import Paginator


def main_view(request, sample_id):
	user = request.user
	sample = Sample.objects.get(id=sample_id)
	return render_to_response('analysis/main.html', locals())

def main_add(request, sample_id):
	sample = Sample.objects.get(id=sample_id)
	return render_to_response('analysis/main_add.html', locals())

def main_manage(request, sample_id):
	sample = Sample.objects.get(id=sample_id)
	return render_to_response('analysis/main_manage.html', locals())

def add_analysis(request, sample_id):
	sample = Sample.objects.get(id=sample_id)
	if request.method == 'POST':
		attr = models.AnalysisAttribute(sample=sample,
			date_time_last_updated=datetime.datetime.now(), last_updated_by=request.user)
		form = forms.AddAnalysisForm(request.POST, instance=attr)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/analysis/main/%s' % sample_id)
	form = forms.AddAnalysisForm()
	analysed_aliquots = models.AnalysisAttribute.objects.filter(sample__id=sample_id).values('aliquot_id')
	# purify the ids into a list
	vals = [ aa['aliquot_id'] for aa in analysed_aliquots]
	print vals
	aliquot_dict = {}
	# Free: true
	# Analysed: false
	for i in range(1,sample.aliquot_no+1): # +1: because aliquot numbers start from one not zero.
		aliquot_dict[i] = str(i) not in vals
	print aliquot_dict
	return render_to_response('analysis/analysis_add.html', locals())

def add_analysis_type(request):
	if request.method == 'POST':
		atype = models.AnalysisType(date_time_last_updated=datetime.datetime.now(), last_updated_by=request.user)
		form = forms.AddAnalysisTypeForm(request.POST, instance=atype)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/analysis/attr/add')
	analysis_type_form = forms.AddAnalysisTypeForm()
	return render_to_response('analysis/analysis_type_add.html', locals())

def add(request):
	form = forms.AddAnalysisForm()
	if request.method == 'POST':
		attr = models.AnalysisAttribute(date_time_last_updated=datetime.datetime.now(), last_updated_by=request.user)
		form = forms.AddAnalysisForm(request.POST, instance=attr)
		if form.is_valid():
			form.save()
			# update sample i.e. increase aliquot number by one
			sample = form.instance.sample
			if sample.aliquot_no is None:
				sample.aliquot_no = 1
			else:
				sample.aliquot_no = sample.aliquot_no + 1
			sample.save()
			success = True

	subscribed_projects = request.user.project_subscriptions.all()
	form.fields['sample'].queryset = Sample.objects.filter(subject__project__in=subscribed_projects)
	return render_to_response('analysis/add_attr.html', locals())

def get_sample_attributes(request, sample_id):
	q = request.GET['q']
	analysis_attributes = models.AnalysisAttribute.objects.filter(name__icontains=q, sample__id=sample_id).values('name').distinct()
	name_list = [attr['name'] + '\n' for attr in analysis_attributes]
	return HttpResponse(name_list)

def get_attributes_by_analysis_type(request, analysis_type_id):
	q = request.GET['q']
	if q == '*':
		analysis_attributes = models.AnalysisAttribute.objects.all().values('name').distinct()
	else:
		analysis_attributes = models.AnalysisAttribute.objects.filter(name__icontains=q, analysis_type__id__exact=analysis_type_id).values('name').distinct()
	name_list = [attr['name'] + '\n' for attr in analysis_attributes]
	return HttpResponse(name_list)

def show_by_sample(request, sample_id, page_num=1):
	""" Lists all the analysis page by page """
	sample = Sample.objects.get(id=sample_id)
	query = models.AnalysisAttribute.objects.filter(sample=sample)
	filtered = False
	if 'showvalue' in request.GET and request.GET['showvalue']:
		query = query.filter(value__isnull=False)		
		filtered=True
	paginator = Paginator(query.order_by('-date_time_last_updated'), 10)
	page = paginator.page( page_num )
	analyses = page.object_list
	return render_to_response('analysis/show_by_sample.html', locals())

def edit(request, analysis_id):
	user = request.user
	subscriptions = user.project_subscriptions.all()
	analysis = models.AnalysisAttribute.objects.get(id=analysis_id)
	if request.method == 'POST':
		analysis.date_time_last_updated=datetime.datetime.now()
		analysis.last_updated_by=user
		form = forms.AddAnalysisForm(request.POST, instance=analysis)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/analysis/show/bysample/%s/1' % analysis.sample.id)
	form = forms.AddAnalysisForm(instance=analysis)
	return render_to_response('analysis/edit.html', locals())

def delete(request, analysis_id):
	user = request.user
	analysis = models.AnalysisAttribute.objects.get(id=analysis_id)
	if request.method == 'POST':
		sample_id = analysis.sample.id
		if analysis.sample.aliquot_no is not None:
			analysis.sample.aliquot_no = analysis.sample.aliquot_no - 1
			analysis.sample.save()
		analysis.delete()
		return HttpResponseRedirect('/analysis/show/bysample/%s/1' % sample_id)
	return render_to_response('analysis/delete.html', locals())

templates/analysis/add.html
{% extends 'project_perspective.html'%}

{%block toolbarpane%}
	Samples &#187; {{sample}} &#187; Add new analysis
{%endblock%}

{% block centerpane %}
<form action="/analysis/bysample/{{sample.id}}" method="POST">
	<table class="form_table">
	{{form.as_table}}
	</table>
	<p><input type="submit" value="Add" /></p>
</form>
{% endblock %}

templates/analysis/add_attr.html
{%extends 'base.html'%}

{%block extrahead%}
<link rel="stylesheet" href="/site_media/css/jquery.autocomplete.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/css/master.css" type="text/css" media="screen" title="no title" charset="utf-8">
<script src="/site_media/js/jquery.autocomplete.min.js" type="text/javascript"></script>
<script src="/site_media/js/jquery.qtip-1.0.0-beta4.min.js" type="text/javascript" charset="utf-8"></script>
{%endblock%}
{%block contentcolumn%}
<div class="breadcrumb">
	Analysis &#187; Add Attribute
</div>
<div class="left_col">
   	{% if form.errors %}
		<b>Solve the errors below</b>
    {% endif %}
	<a id="new_analysis_info" href="/analysis/main/add/analysis_type?width=400&height=100" title="New Analysis Type" class="thickbox">Add New Analysis Type</a> 
	<form action="/analysis/attr/add" method="POST">
		<table class="form_table">
			<tr>		
			{{form.as_table}}
			<tr>
				<td>&nbsp;</td>
				<td>
				<input type="submit" name="submit" id="id_submit_button" value="Add"/>
				<input type="button" name="cancel" id="id_cancel_button" value="Cancel" onclick="javascript:history.back();"/>	
				</td>
			</tr>
		</table>
	</form>	
	</div>
	<div class="rdescription">
					<h3>Help</h3>
                    Sample list is generated only from the projects you subscribed.
                    <em>Name</em> is autocompleted by looking at the <em>Analysis Type</em>.
				<h3>Where am I?</h3>
						<ul>
							<li>Analysis
								<ul>
									<li>Create Attribute</li>
								</ul>
							</li>
						</ul>
	</div>

    <div id="messageDiv">
        {%if success %}
            <b>Saved successfully!</b>
        {%endif%}
    </div>
<script>
	$('.rdescription').corner("bottom");
	$('.messageDiv').corner();
	$("#id_analysis_type").change( function() {
	var selected_analysis_type = $('#id_analysis_type').val();
		$('#id_name').autocomplete("/analysis/attributes/byanalysis_type/"+selected_analysis_type);
	});
    $(document).ready( function() {
        $('#messageDiv').fadeOut(5000);
    } );
    
    $('#new_analysis_info').qtip({
    	content: 'You can add your own analysis type if you cannot find it on the list below.',
    	position: {
    		corner:{
    			target: 'rightMiddle',
    			tooltip: 'leftMiddle'
    		}
    	}
    });
    
    
</script>
{%endblock%}

templates/analysis/analysis_add.html
	<form action="/analysis/main/add/analysis/{{sample.id}}" method="POST">
		<table class="form_table">
		<tr>
			<td>
				Analysis Type:</td><td>
				{{form.analysis_type}}
				| <a href="#" onclick="$('#addmenu').tabs('select', 1);">Or Add a new type</a>
			</td>
		</tr>
		<tr><td>Analysis Attribute:</td><td>{{form.name}}</td></tr>
		<tr><td>Attribute Value:</td><td>{{form.value}}</td></tr>
		<tr><td>Which aliquot:</td>
			<td>
		
				<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					{%for k,v in aliquot_dict.items %}
				      <td>
				      	{%if not v%}
				      		<img class="notready" src="/site_media/images/minus-circle.png" border="0"/>
				      	{%else%}
				      		<img src="/site_media/images/pipette.png" border="0"/>
				      	{%endif%}
				      </td>
				   	{%endfor%}
				</tr>
				<tr>
					{%for k,v in aliquot_dict.items %}
				      <td>
				      	{%if not v%}
				      		<img class="notready" src="/site_media/images/pencil.png" border="0"/>
				      	{%else%}
							<input type="radio" name="aliquot_id" value="{{k}}"/>
				      	{%endif%}
				      </td>
				   	{%endfor%}
				</tr>
				<tr>
					{%for k,v in aliquot_dict.items %}
				      <td>
				      	{%if not v%}
				      		{{k}}
				      	{%else%}
				      		<b>{{k}}</b>
				      	{%endif%}
				      </td>
				   	{%endfor%}
				</tr>								
				</table>
			</td>
		</tr>	
		<tr>
			<td>&nbsp;</td>
			<td><input type="submit" name="submit" id="id_submit" value="Add"/></td>
		</tr>
		</table>
	</form>

<script>
	$("#id_analysis_type").change( function() {
		var selected_analysis_type = $('#id_analysis_type').val();
		console.log("analysis type==>" + selected_analysis_type);
		$('#id_name').autocomplete("/analysis/attributes/byanalysis_type/"+selected_analysis_type);
	});

	$('.notready').qtip({
	  		 content: 'This feature is not ready for this release.',
	  		 show: 'mouseover',
	  		 hide: 'mouseout',
			   position: {
				  corner: {
					 target: 'topRight',
					 tooltip: 'bottomLeft'
				  }
			   },
		    style: { 
		      tip: 'bottomLeft'
   			}

	});	
</script>

templates/analysis/analysis_manage.html
{% extends 'project_perspective.html'%}

{%block toolbarpane%}
	{{sample.subject}} &#187; {{sample}} &#187; Analyses &#187; Add
{%endblock%}

{% block centerpane %}

<div id="tabs">
     <ul>
         <li><a href="/analysis/bysample/{{sample.id}}" title="View"><span>View</span></a></li>
         <li><a href="/analysis/add/" title="Add"><span>Add</span></a></li>
         <li><a href="/analysis/manage/" title="Manage"><span>Manage</span></a></li>
     </ul>

<div id="Manage">
	<p>Manage Attribute types</p>
</div>

<script>
	$('#id_name').autocomplete('/analysis/attributes/bysample/{{sample_id}}');
	$('#analysis_table').colorize({bgColor:'#EAF6CC', hoverColor:'#cce',  oneClick:false});
	$('#tabs').tabs();
	$('.editImg').qtip({
	  		 content: 'Edit',
	  		 show: 'mouseover',
	  		 hide: 'mouseout',
			   position: {
				  corner: {
					 target: 'topMiddle',
					 tooltip: 'bottomMiddle'
				  }
			   },
		    style: { 
		      tip: 'bottomMiddle'
   			}

	});
	$('.deleteImg').qtip({
	  		 content: 'Remove',
	  		 show: 'mouseover',
	  		 hide: 'mouseout',
			   position: {
				  corner: {
					 target: 'topMiddle',
					 tooltip: 'bottomMiddle'
				  }
			   },
		    style: { 
		      tip: 'bottomMiddle'
   			}

	});	
	$('.monitorImg').qtip({
	  		 content: 'Analysis',
	  		 show: 'mouseover',
	  		 hide: 'mouseout',
			   position: {
				  corner: {
					 target: 'topMiddle',
					 tooltip: 'bottomMiddle'
				  }
			   },
		    style: { 
		      tip: 'bottomMiddle'
   			}
	});	

</script>

{%endblock%}

templates/analysis/analysis_type_add.html
<div id="Add">
	<form id="analysis_type_form" action="/analysis/main/add/analysis_type" method="POST">
		<table class="form_table">
			{{analysis_type_form.as_table}}
			<tr>	
				<td>&nbsp;</td>
				<td><input type="submit" name="submit" id="id_submit" value="Add"/></td>
			</tr>			
		</table>
	</form>
</div>

templates/analysis/analysis_view.html
<div id="View">
	{%ifequal analyses.count 0%}
		<img src="/site_media/images/minus-circle.png" border="0"><span class="warning">
			No analysis found.</span> Add a new analysis using the form below.
	{%else%}	
		<table id="analysis_table" border="0" cellspacing="0" cellpadding="0" width="100%">
			<thead>
				<tr>
				<th>Aliquot Id</th>
				<th>Analysis Type</th>
				<th>Attribue</th>
				<th>Value</th>
				<th>Last Updated By</th>
				<th>Date Last Updated </th>
				<th>Time Last Updated </th></tr>
			</thead>

			<tbody>
				{%for analysis in analyses %}
				<tr>
				   <td>
				   		<a href="/analysis/edit/{{analysis.id}}"><img class="editImg" src="/site_media/images/pencil.png" border="0"/></a>
				   		<a href="/analysis/delete/{{analysis.id}}"><img class="deleteImg" src="/site_media/images/cross.png" border="0"/></a>	   		
				   		{{analysis.aliquot_id}}
				   </td>
				   <td>{{analysis.analysis_type}}</td>
				   <td>{{analysis.name}}</td>
				   <td>{{analysis.value}}</td>	   	   	   
				   <td>{{analysis.last_update_by}}</td>	   	   	   
				   <td>{{analysis.date_time_last_updated|date}}</td>
				   <td>{{analysis.date_time_last_updated|time}}</td>	   	   	   	   	   	   	   	   	   	   	   
				</tr>		
				{%endfor%}
		</tbody>
	</table>
		<div class="table_page_nav">
			{%if page.has_previous %}
				<a href="/analysis/show/bysample/{{sample_id}}/{{page.previous_page_number}}">&lt;&lt; Prev</a>
			{%endif%}
		
			{{page}}

			{%if page.has_next %}
				<a href="/analysis/show/bysample/{{sample_id}}/{{page.next_page_number}}">Next &gt;&gt;</a>
			{%endif%}		
		</div>
	{%endifequal%}
</div>

templates/analysis/delete.html
{%extends 'base.html'%}

{%block contentcolumn%}
<div class="breadcrumb">
	Analysis &#187; Delete
</div>
<div class="left_col">
	<img src="/site_media/images/exclamation.png" border="0"/>
    <b>Are you sure to continue to delete this analysis?</b>
	<form action="/analysis/delete/{{analysis.id}}" method="POST">
		<input type="submit" name="submit" id="id_submit" value="Yes, Delete the sample">
		<input type="button" name="cancel" id="id_cancel" value="No, Go back" onclick="javascript:history.back();"/>
	</form>
</div>
<div class="rdescription">
					<h3>Help</h3>
                    All analysis data will be removed permanently. Please be aware of what you are doing.
					<h3>Where am I?</h3>
						<ul>
							<li>Analysis
								<ul>
									<li>Delete</li>
								</ul>
							</li>
						</ul>

</div>
<script>
	$('.rdescription').corner("bottom");
</script>

{%endblock%}

templates/analysis/edit.html
{% extends 'base.html'%}

{%block extrahead%}
<link rel="stylesheet" href="/site_media/css/jquery.autocomplete.css" type="text/css" media="screen"/>
<script src="/site_media/js/jquery.autocomplete.min.js" type="text/javascript"></script>
{%endblock%}
{%block contentcolumn%}
<div class="breadcrumb">
	Analysis &#187; Edit Attribute
</div>
<div class="left_col">
   	{% if form.errors %}
		<b>Solve the errors below</b>
    {% endif %}
	<form action="/analysis/edit/{{analysis.id}}" method="POST">
		<table class="form_table">
			{{form.as_table}}
			<tr>
				<td>&nbsp;</td>
				<td>
				<input type="submit" name="submit" id="id_submit_button" value="Update"/>
				<input type="button" name="cancel" id="id_cancel_button" value="Cancel" onclick="javascript:history.back();"/>	
				</td>
			</tr>
		</table>
	</form>
	</div>

	<div class="rdescription">
					<h3>Help</h3>
                    Sample list is generated only from the projects you subscribed.
                    <em>Name</em> is autocompleted by looking at the <em>Analysis Type</em>.
				<h3>Where am I?</h3>
						<ul>
							<li>Analysis
								<ul>
									<li>Create Attribute</li>
								</ul>
							</li>
						</ul>
	</div>

    <div id="messageDiv">
        {%if success %}
            <b>Saved successfully!</b>
        {%endif%}
    </div>
<script>
	$('.rdescription').corner("bottom");
	$('.messageDiv').corner();
	$("#id_analysis_type").change( function() {
	var selected_analysis_type = $('#id_analysis_type').val();
		$('#id_name').autocomplete("/analysis/attributes/byanalysis_type/"+selected_analysis_type);
	});
    $(document).ready( function() {
        $('#messageDiv').fadeOut(5000);
    } );
</script>
{%endblock%}

templates/analysis/main.html
{% extends 'base.html'%}

{% block contentcolumn %}

<div id="tabs" class="tabbedPane">
     <ul>
         <li><a href="/analysis/show/bysample/{{sample.id}}/1"><span>List Analyses for {{sample}}</span></a></li>
         <li><a href="#add"><span>Add</span></a></li>
         <li><a href="/analysis/manage/{{sample.id}}"><span>Manage</span></a></li>
     </ul>
	<div id="add">
		<div id="addmenu">
			 <ul>
				 <li><a href="/analysis/main/add/analysis/{{sample.id}}"><span>Analysis</span></a></li>
				 <li><a href="/analysis/main/add/analysis_type/{{sample.id}}"><span>Analysis Type</span></a></li>
			 </ul>
		</div>
	</div>
</div>
<script>
	$('#id_name').autocomplete('/analysis/attributes/bysample/{{sample_id}}');
	$('#analysis_table').colorize({bgColor:'#EAF6CC', hoverColor:'#cce',  oneClick:false});
	$('#tabs').tabs();
	$('#addmenu').tabs();
	$('.editImg').qtip({
	  		 content: 'Edit',
	  		 show: 'mouseover',
	  		 hide: 'mouseout',
			   position: {
				  corner: {
					 target: 'topMiddle',
					 tooltip: 'bottomMiddle'
				  }
			   },
		    style: {
		      tip: 'bottomMiddle'
   			}

	});
	$('.deleteImg').qtip({
	  		 content: 'Remove',
	  		 show: 'mouseover',
	  		 hide: 'mouseout',
			   position: {
				  corner: {
					 target: 'topMiddle',
					 tooltip: 'bottomMiddle'
				  }
			   },
		    style: {
		      tip: 'bottomMiddle'
   			}

	});
	$('.monitorImg').qtip({
	  		 content: 'Analysis',
	  		 show: 'mouseover',
	  		 hide: 'mouseout',
			   position: {
				  corner: {
					 target: 'topMiddle',
					 tooltip: 'bottomMiddle'
				  }
			   },
		    style: {
		      tip: 'bottomMiddle'
   			}
	});

</script>

{% endblock %}

templates/analysis/main_add.html
<div class="tabbedPane">
     <ul>
         <li><a href="/analysis/main/add/analysis/{{sample.id}}"><span>Analysis</span></a></li>
         <li><a href="/analysis/main/add/analysis_type/{{sample.id}}"><span>Analysis Type</span></a></li>
     </ul>
</div>